services:
  mysql:
    image: mysql:8.4
    container_name: moodle52-mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-file-per-table=1
    environment:
      MYSQL_ROOT_PASSWORD: root_moodle52
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle52
      TZ: America/Bogota
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
